language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build
  - docker tag reverseproxy rodgersimiyu/reverseproxy:v1
  - docker tag udagram-api-feed rodgersimiyu/udagram-api-feed:v1
  - docker tag udagram-api-user rodgersimiyu/udagram-api-user:v1
  - docker tag udagram-frontend rodgersimiyu/udagram-frontend:v1

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push rodgersimiyu/udagram-api-feed:v1
  - docker push rodgersimiyu/udagram-api-user:v1
  - docker push rodgersimiyu/udagram-frontend:v1
  - docker push rodgersimiyu/reverseproxy:v1
