apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
  labels:
    app: udagram-api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
      - name: backend-user
        image: rodgersimiyu/udagram-api-user:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1024Mi"
            cpu: "400m"
          limits:
            memory: "2048Mi"
            cpu: "700m"
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: aws-secret-volume
            mountPath: /root/.aws
        envFrom:
          - configMapRef:
              name: udagram-configmap
          - secretRef:
              name: udagram-secret
      restartPolicy: Always
      volumes:
        - name: aws-secret-volume
          secret:
            secretName: aws-secret
            items:
            - key: credentials
              path: credentials